name: my_project
description: "A new Flutter project."

publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.5.4



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  molten_navigationbar_flutter: ^1.0.1
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  supabase_flutter: ^2.8.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  badges: ^3.1.2
  intl: ^0.20.2
  flutter_colorpicker: ^1.0.3

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

assets:
  - images/
    
